#:schema node_modules/wrangler/config-schema.json
name = "aroundy-cdn"
main = "src/index.ts"
compatibility_date = "2024-07-12"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "aroundy"
